name: campus_connect
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  email_validator: ^2.1.17
  flutter_secure_storage: ^8.0.0
  material_design_icons_flutter: ^6.0.7096
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  firebase_storage: ^11.0.16
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
